# Goal
string command
string episode_type  # shape/slip
bool reset_rig

---
# Result
int32 iterations 
bool result 
string bag_path

---
# Feedback
int32 current_iteration
float64 angle
string bag_path 
bool result